BEGIN;

ALTER TABLE public."User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."CustomerProfile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."DriverProfile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Vehicle" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Route" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."RoutePrice" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."RideQuote" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Booking" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."BookingStop" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Invoice" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."PaymentTransaction" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."PaymentEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Notification" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."AuditLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."PasswordResetToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."EmailVerificationToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."PhoneVerificationCode" ENABLE ROW LEVEL SECURITY;

COMMIT;
